apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  volumes:
    - name: webcontent
      persistentVolumeClaim:
        claimName: devops-pv-claim
  containers:
    - name: hello1
      image: rvegesna/cetos:web2
      volumeMounts:
        - mountPath: "/var/www/html"
          name: webcontent

