apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
 name: devops
spec:
 replicas: 2
 selector:
   matchLabels:
      app: webserver 
 template:
   metadata:
     labels:
        app: webserver
   spec:
     containers:
       - name: devops1
         image: rvegesna/cetos:web2
