apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: webserver
  type: NodePort  
  ports:
  - name: webserver
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30123
